menu:
  主页: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于我: /about
ads:
# 站点次标题和打字动效
# https://github.com/mattboldt/typed.js
subtitle:
  enable: true # 是否开启动效
  text: 积累、总结，不断学习 # 显示的文字
  text2: 愿你一生努力，一生被爱 # 滚动播放，如果不需要可以留空
  text3: 想要的都拥有，得不到的都释怀 # 最多支持三段文字
  startDelay: 0 # 延迟时间
  typeSpeed: 200 # 打字速度
  loop: true # 是否循环
  backSpeed: 100 # 回退速度
  showCursor: true # 是否显示光标
# 是否开启代码复制按钮
copy_btn: true
# 是否启用搜索
search: true
# 是否启用黑夜模式开关
darkmode: false
# GitHub Ribbons-封面右上角的forkme，换样式直接在source/images目录下替换forkme图片
github:
  # (关闭请设置为false)
  enable: false
  url: https://github.com/visonforcoding
# 封面配置
# enable-是否启用封面；path-封面背景图；logo-封面logo
cover:
  enable: false
  path: /images/cover1.jpg # /source/images目录下附送多张精美壁纸，可任意更换
  logo: /images/ayer.svg # 如果不要直接设置成false
# type：0-close reward； 1-only open in article which you have configured reward:true； 2-open in all articles
reward_type: 2
# reward word
reward_wording: "Buy me a cup of coffee~"
# qrcode image path
alipay: /images/alipay.jpeg
# qrcode image path
weixin: /images/wallet.png